### ISSUE TITLE
 MigrateProjects << No project name matched 

### ISSUE THREAD

**Issue by evaldasou** [shuLhan/j2p#3]
Thanks a lot for Your effort when building this tool, however j2p output looks like this:

 ./j2p tasks output:
[j2p] MigrateProjects << No project name matched with 'Architecture'
[j2p] MigrateProjects << No project name matched with 'Core'
[j2p] MigrateProjects << No project name matched with 'Test'

Those projects are above are in Jira , not in Phabricator. I have tried same command when project names are created in Phabricator, but output is the same. Anything I'm missing here?

Thanks again!

**Comment by shuLhan** [comment]
What version of Phabricator did you use?

**Comment by evaldasou** [comment]
I have spinned up it from docker container as here : https://hub.docker.com/r/yesnault/docker-phabricator/
All settings -> Current version says: 
Phabricator Version Unknown 
Arcanist Version Unknown 
libphutil Version Unknown

What version You could recommend to use?

Thanks

**Comment by shuLhan** [comment]
> What version You could recommend to use?

I recommend the latest version. When I was develop this tool, I installed Phabricator using the git master branch. I will try to test it into your docker version later.

**Comment by evaldasou** [comment]
So I have tested not on docker directly this time... Installation is very painful (that's why I tried docker in first place).

At the moment program works okay, and I have migrated part of the projects and tasks, however program crashes with the output below:

[j2p] MigrateTasks ERROR >> &{0xc420195320 0 0 0}panic: Request failed. Please analyze the request body for more details. Status code: 400

goroutine 1 [running]:
panic(0x6289c0, 0xc4202390b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /root/work/work/src/github.com/j2p/cmd/j2p/main.go:76 +0xee

Any idea why this could happen?
Also, is it possible to assign migrated tasks/ projects to same users as it was on jira?

**Comment by evaldasou** [comment]
ShuLhan any ideas? What could I try? :)

**Comment by shuLhan** [comment]
> Any idea why this could happen?

I have no idea. But looking from status code, 400, it means some request have invalid parameters.

> Also, is it possible to assign migrated tasks/ projects to same users as it was on jira?

I'm sorry, its not possible, because mapping user, comments, and attachments between JIRA and Phabricator its not easy.

> ShuLhan any ideas? What could I try? :) 

Sorry, I don't have time to investigate it. I will comment it later if I find the problem and solution.
